apiVersion: v1
kind: Service
metadata:
  name: my-docker
  labels:
    run: my-docker
spec:
  type: NodePort # Service 의 Type 을 명시하는 부분입니다. 
  ports:
  - port: 8000
    protocol: TCP
  selector: # 아래 label 을 가진 Pod 을 매핑하는 부분입니다.
    app: cnu-docker 